version: '2'
services:
    restaurantmanagement-app:
        image: restaurantmanagement
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://restaurantmanagement-postgresql:5432/RestaurantManagement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    restaurantmanagement-postgresql:
        extends:
            file: postgresql.yml
            service: restaurantmanagement-postgresql
